
fluentd_conf_directory: /etc/fluentd
fluentd_conf_file_name: "fluentd.conf"
fluentd_conf_file_path: "{{ fluentd_conf_directory }}/{{ fluentd_conf_file_name }}"

es_scheme: http
es_host: 192.168.56.46
es_port: 9200
es_user: ''
